language: php
sudo: false

php:
 - 5.6

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - "hiptest-publisher -c behat.conf --only=features,step_definitions --test-run-id=16135"
  - composer install

script:
  - vendor/bin/behat -f junit

after_script:
  - hiptest-publisher -c behat.conf --push=results/report.xml --test-run-id=16135
